const translations={
  en:{
    switch:"🌐 Español",navOfferings:"Offerings",navHerbs:"Herb library",navFortune:"Your fortune",navLocations:"Locations",call:"Call us",eyebrow:"Herbs · Botánica · Wellness",intro:"A welcoming neighborhood botánica filled with tradition, intention and a little everyday magic.",introDetail:"After more than 15 years serving Santa Fe, we’re bringing the best of our selection to Albuquerque. Find religious goods of every kind, including candles, saints, devotional images and jewelry; herbs such as arnica, chamomile, cota, riñosán, osha, eucalyptus and much more; plus incense, oils and spiritual waters. If you have questions, call either of our two locations for more information.",follow:"Follow us",viewLocations:"View our locations",abqStore:"Albuquerque store",abqBrief:"Sun–Fri · 11 AM–6 PM · Closed Sat",tradition:"Tradition",intention:"Intention",wellness:"Wellness",community:"Community",hello:"Come say hello",visitOur:"Visit our",twoLocations:"two locations.",hours:"Hours",contact:"Contact",abqDays:"Sunday–Friday",closedSat:"Closed Saturday",sfDays:"Monday–Saturday",closedSun:"Closed Sunday",directions:"Get directions ↗",explore:"Explore the shop",meaningful:"Something meaningful<br>for every intention.",offeringNote:"Whether you are honoring a tradition, refreshing your space or looking for a thoughtful gift, we are happy to help you find what feels right.",saintsEyebrow:"Devotional goods",saintsTitle:"Offering Saints, different sizes.",spiritualEyebrow:"Guidance · Tradition · Intention",spiritualTitle:"Spiritual Offerings",spiritualIntro:"Personal spiritual services offered with care and respect for tradition.",gift:"A little gift for you",future:"What does your future hold?",reveal:"Reveal my fortune",fortuneNote:"Made with good intentions. Tap as often as your spirit needs.",waiting:"Your message is waiting inside the crystal ball.",libraryEyebrow:"Our herb collection",libraryTitle:"Explore our herb library.",libraryIntro:"Search the herbs carried at Yerbería Santa Fe by name or traditional use.",search:"Search herbs or traditional uses…",all:"All",showing:"Showing",herbs:"herbs",traditionalUse:"Traditional use",storeArea:"Store area",collapseLibrary:"Minimize library",expandLibrary:"Show library",availability:"Selection and availability may vary by location. Please call before visiting for a specific herb.",notice:"Important notice",disclaimer:"Educational information only. Traditional uses are not medical advice and are not intended to diagnose, treat, cure or prevent disease. Consult a qualified healthcare professional, especially during pregnancy, while taking medication, or for serious symptoms.",noResults:"No herbs match your search.",loadError:"The herb list could not be loaded."
  },
  es:{
    switch:"🌐 English",navOfferings:"Productos",navHerbs:"Biblioteca de hierbas",navFortune:"Tu fortuna",navLocations:"Ubicaciones",call:"Llámanos",eyebrow:"Hierbas · Botánica · Bienestar",intro:"Una botánica acogedora llena de tradición, intención y un poquito de magia cotidiana.",introDetail:"Con más de 15 años sirviendo a Santa Fe, ahora traemos a Albuquerque lo mejor de nuestra selección. Encontrarás artículos religiosos de todo tipo, incluyendo velas, santos, imágenes y joyería; hierbas como árnica, manzanilla, cota, riñosán, osha, eucalipto y mucho más; además de incienso, aceites y aguas espirituales. Si tienes preguntas, llama a cualquiera de nuestras dos ubicaciones para obtener más información.",follow:"Síguenos",viewLocations:"Ver ubicaciones",abqStore:"Tienda de Albuquerque",abqBrief:"Dom–Vie · 11 AM–6 PM · Cerrado Sáb",tradition:"Tradición",intention:"Intención",wellness:"Bienestar",community:"Comunidad",hello:"Ven a visitarnos",visitOur:"Visita nuestras",twoLocations:"dos ubicaciones.",hours:"Horario",contact:"Contacto",abqDays:"Domingo–Viernes",closedSat:"Cerrado los sábados",sfDays:"Lunes–Sábado",closedSun:"Cerrado los domingos",directions:"Cómo llegar ↗",explore:"Explora la tienda",meaningful:"Algo especial<br>para cada intención.",offeringNote:"Ya sea que honres una tradición, renueves tu espacio o busques un regalo especial, con gusto te ayudamos a encontrar lo indicado.",saintsEyebrow:"Artículos de devoción",saintsTitle:"Ofrecemos santos en diferentes tamaños.",spiritualEyebrow:"Guía · Tradición · Intención",spiritualTitle:"Servicios espirituales",spiritualIntro:"Servicios espirituales personales ofrecidos con cuidado y respeto por la tradición.",gift:"Un regalito para ti",future:"¿Qué te depara el futuro?",reveal:"Descubre mi fortuna",fortuneNote:"Hecho con buenas intenciones. Toca cuantas veces lo necesite tu espíritu.",waiting:"Tu mensaje te espera dentro de la bola de cristal.",libraryEyebrow:"Nuestra colección de hierbas",libraryTitle:"Explora nuestra biblioteca de hierbas.",libraryIntro:"Busca las hierbas que ofrecemos en Yerbería Santa Fe por nombre o uso tradicional.",search:"Busca una hierba o un uso tradicional…",all:"Todas",showing:"Mostrando",herbs:"hierbas",traditionalUse:"Uso tradicional",storeArea:"Área en la tienda",collapseLibrary:"Minimizar biblioteca",expandLibrary:"Mostrar biblioteca",availability:"La selección y disponibilidad puede variar por ubicación. Llámanos antes de visitar si buscas una hierba específica.",notice:"Aviso importante",disclaimer:"Información educativa solamente. Los usos tradicionales no constituyen consejo médico ni están destinados a diagnosticar, tratar, curar o prevenir enfermedades. Consulta con un profesional de salud, especialmente durante el embarazo, si tomas medicamentos o si tienes síntomas graves.",noResults:"Ninguna hierba coincide con tu búsqueda.",loadError:"No se pudo cargar la lista de hierbas."
  }
};

const offerings={
  en:[["❧","HIERBAS","Herbs","A thoughtful selection of traditional herbs and herbal goods."],["♧","VELAS","Candles","Prayer, intention, devotion, cleansing and celebration candles."],["♢","ACEITES","Oils","Spiritual and aromatic oils selected for meaningful intentions."],["✦","INCIENSO","Incense & spiritual goods","Fragrant incense, waters, charms, devotional items and gifts."]],
  es:[["❧","HIERBAS","Hierbas","Una selección especial de hierbas tradicionales y productos herbales."],["♧","VELAS","Veladoras","Velas para oración, intención, devoción, limpieza y celebración."],["♢","ACEITES","Aceites","Aceites espirituales y aromáticos seleccionados para intenciones especiales."],["✦","INCIENSO","Incienso y artículos espirituales","Inciensos, aguas, amuletos, artículos religiosos y regalos."]]
};

const spiritual={
  en:[["✧","Energy Cleansings","Limpias Energéticas"],["♢","Card Readings","Lectura de cartas"],["☾","Tarot Readings","Lectura de tarot"],["☕","Turkish Coffee Consultations","Consulta con café turco"],["✋","Palm Readings","Lectura de la palma de la mano"]],
  es:[["✧","Limpias Energéticas","Energy Cleansings"],["♢","Lectura de Cartas","Card Readings"],["☾","Lectura de Tarot","Tarot Readings"],["☕","Consulta con Café Turco","Turkish Coffee Consultations"],["✋","Lectura de la Palma de la Mano","Palm Readings"]]
};

const fortunes={
  en:["A beautiful new beginning is already finding its way to you.","Your kindness will return to you in an unexpected form.","Trust the quiet progress you cannot see yet.","A joyful surprise will brighten an ordinary day.","You are closer to your dream than you think.","The courage you show today will open tomorrow’s door.","Your next chapter carries more light than the last."],
  es:["Un hermoso nuevo comienzo ya viene en camino hacia ti.","Tu bondad regresará a ti de una manera inesperada.","Confía en el progreso silencioso que aún no puedes ver.","Una sorpresa alegre iluminará un día ordinario.","Estás más cerca de tu sueño de lo que imaginas.","El valor que demuestres hoy abrirá la puerta del mañana.","Tu próximo capítulo trae más luz que el anterior."]
};

const minorWords=new Set(["de","del","la","las","el","los","y","e","o","en","con","para","por","of","the","and","or","in","with","for"]);
let language="en",herbs=[],activeLetter="ALL",query="",libraryExpanded=true;

function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c])}
function titleCase(value){return value.trim().toLocaleLowerCase().split(/\s+/).map((word,index)=>index>0&&minorWords.has(word)?word:word.replace(/(^|[-/('’])(\p{L})/gu,(_,separator,letter)=>separator+letter.toLocaleUpperCase())).join(" ")}
function sentenceCase(value){const original=value.trim();if(!original)return "";const acronyms=new Map();(original.match(/\b[A-ZÁÉÍÓÚÑ]{2,5}\b/g)||[]).forEach(word=>acronyms.set(word.toLocaleLowerCase(),word));const normalized=original.toLocaleLowerCase().replace(/(^|[.!?]\s+)(\p{L})/gu,(_,prefix,letter)=>prefix+letter.toLocaleUpperCase());return normalized.replace(/\b[a-záéíóúñ]{2,5}\b/gu,word=>acronyms.get(word)||word)}
function parseCsv(text){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++}else if(c==='"'){quoted=!quoted}else if(c===","&&!quoted){row.push(cell.trim());cell=""}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&text[i+1]==="\n")i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=""}else cell+=c}if(cell||row.length){row.push(cell.trim());rows.push(row)}return rows.slice(1).filter(r=>r[0]).map(r=>({name:r[0]||"",useCase:r[1]||"",location:r[3]||"",price:r[5]||""}))}

function renderOfferings(){document.getElementById("offeringGrid").innerHTML=offerings[language].map(x=>'<article class="offering-card"><span class="offering-icon">'+x[0]+'</span><div class="ornament-line"><i></i><b>•</b><i></i></div><h3>'+x[1]+'</h3><h4>'+x[2]+'</h4><p>'+x[3]+'</p></article>').join("")}
function renderSpiritual(){document.getElementById("spiritualGrid").innerHTML=spiritual[language].map(x=>'<article class="spiritual-card"><span class="spiritual-icon" aria-hidden="true">'+x[0]+'</span><div><h4>'+x[1]+'</h4><p>'+x[2]+'</p></div></article>').join("")}
function renderLetters(){const letters=[...new Set(herbs.map(h=>h.name.charAt(0).toLocaleUpperCase()))].sort((a,b)=>a.localeCompare(b));document.getElementById("letterFilter").innerHTML=["ALL"].concat(letters).map(x=>'<button type="button" data-letter="'+escapeHtml(x)+'" class="'+(activeLetter===x?"active":"")+'">'+(x==="ALL"?translations[language].all:x)+'</button>').join("");document.querySelectorAll("[data-letter]").forEach(button=>button.addEventListener("click",function(){activeLetter=this.dataset.letter;renderLetters();renderHerbs()}))}
function renderHerbs(){const t=translations[language],search=query.trim().toLocaleLowerCase();const filtered=herbs.filter(h=>(activeLetter==="ALL"||h.name.toLocaleUpperCase().startsWith(activeLetter))&&(!search||h.name.toLocaleLowerCase().includes(search)||h.useCase.toLocaleLowerCase().includes(search)));document.getElementById("resultCount").innerHTML=t.showing+" <strong>"+filtered.length+"</strong> "+t.herbs;document.getElementById("herbGrid").innerHTML=filtered.length?filtered.map(h=>{const name=titleCase(h.name);return '<article class="herb-card"><div class="herb-letter">'+escapeHtml(name.charAt(0))+'</div><div><h3>'+escapeHtml(name)+'</h3><p class="use-label">'+t.traditionalUse+'</p><p class="use-case">'+escapeHtml(sentenceCase(h.useCase)||"—")+'</p>'+(h.location?'<p class="store-area"><span>'+t.storeArea+':</span> '+escapeHtml(titleCase(h.location))+'</p>':"")+(h.price?'<p class="herb-price">'+escapeHtml(h.price)+'</p>':"")+'</div></article>'}).join(""):'<div class="herb-empty">'+t.noResults+'</div>'}
function updateLibraryToggle(){const t=translations[language],button=document.getElementById("libraryToggle");button.querySelector("span").textContent=libraryExpanded?t.collapseLibrary:t.expandLibrary;button.querySelector("b").textContent=libraryExpanded?"−":"+";button.setAttribute("aria-expanded",String(libraryExpanded));document.getElementById("herbLibraryContent").hidden=!libraryExpanded}
function setLanguage(next){language=next;document.documentElement.lang=next;const t=translations[next];document.querySelectorAll("[data-t]").forEach(el=>{const value=t[el.dataset.t];if(value!==undefined)el.innerHTML=value});document.getElementById("languageButton").textContent=t.switch;document.getElementById("herbSearch").placeholder=t.search;document.getElementById("herbSearch").setAttribute("aria-label",t.search);document.getElementById("fortuneMessage").textContent="“"+t.waiting+"”";document.getElementById("crystalBall").setAttribute("aria-label",t.reveal);document.getElementById("mainNav").setAttribute("aria-label",next==="en"?"Main navigation":"Navegación principal");document.getElementById("topSocialBar").setAttribute("aria-label",next==="en"?"Yerbería Santa Fe social media":"Redes sociales de Yerbería Santa Fe");document.getElementById("letterFilter").setAttribute("aria-label",next==="en"?"Filter herbs alphabetically":"Filtrar hierbas alfabéticamente");document.getElementById("saintsImage").alt=next==="en"?"Selection of saints offered at Yerbería Santa Fe":"Selección de santos disponibles en Yerbería Santa Fe";renderOfferings();renderSpiritual();renderLetters();renderHerbs();updateLibraryToggle()}
function revealFortune(){const list=fortunes[language],message=document.getElementById("fortuneMessage"),ball=document.getElementById("crystalBall");message.textContent="“"+list[Math.floor(Math.random()*list.length)]+"”";message.classList.remove("revealed");ball.classList.remove("glowing");requestAnimationFrame(()=>{message.classList.add("revealed");ball.classList.add("glowing")})}

document.getElementById("languageButton").addEventListener("click",()=>setLanguage(language==="en"?"es":"en"));
document.getElementById("fortuneButton").addEventListener("click",revealFortune);
document.getElementById("crystalBall").addEventListener("click",revealFortune);
document.getElementById("herbSearch").addEventListener("input",function(){query=this.value;renderHerbs()});
document.getElementById("libraryToggle").addEventListener("click",()=>{libraryExpanded=!libraryExpanded;updateLibraryToggle()});

fetch("herbs.csv").then(response=>{if(!response.ok)throw new Error("load");return response.text()}).then(text=>{herbs=parseCsv(text);renderLetters();renderHerbs()}).catch(()=>{document.getElementById("herbGrid").innerHTML='<div class="herb-empty">'+translations[language].loadError+'</div>'});
setLanguage("en");
